name: clang-format check

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        path:
          - '.'
          - 'include'

    steps:
    - uses: actions/checkout@v4
    - uses: jidicula/clang-format-action@v4.14.0
      with:
        clang-format-version: '19'
        check-path: ${{ matrix.path }}
        include-regex: '.*\.(c|cc|h)'
